/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface AddressCounters
 */
export interface AddressCounters {
  /**
   *
   * @type {string}
   * @memberof AddressCounters
   */
  transactionsCount: string
  /**
   *
   * @type {string}
   * @memberof AddressCounters
   */
  tokenTransfersCount: string
  /**
   *
   * @type {string}
   * @memberof AddressCounters
   */
  gasUsageCount: string
  /**
   *
   * @type {string}
   * @memberof AddressCounters
   */
  validationsCount: string
}
