/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DecodedInputParameter } from './decoded-input-parameter'
/**
 *
 * @export
 * @interface DecodedInput
 */
export interface DecodedInput {
  /**
   *
   * @type {string}
   * @memberof DecodedInput
   */
  methodCall: string
  /**
   *
   * @type {string}
   * @memberof DecodedInput
   */
  methodId: string
  /**
   *
   * @type {Array<DecodedInputParameter>}
   * @memberof DecodedInput
   */
  parameters: Array<DecodedInputParameter>
}
