/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface DecodedInputLogParameter
 */
export interface DecodedInputLogParameter {
  /**
   *
   * @type {string}
   * @memberof DecodedInputLogParameter
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof DecodedInputLogParameter
   */
  type: string
  /**
   *
   * @type {string}
   * @memberof DecodedInputLogParameter
   */
  value: string
  /**
   *
   * @type {boolean}
   * @memberof DecodedInputLogParameter
   */
  indexed: boolean
}
