/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ExternalLibrary
 */
export interface ExternalLibrary {
  /**
   *
   * @type {string}
   * @memberof ExternalLibrary
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof ExternalLibrary
   */
  addressHash: string
}
