/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ExtendedRevertReasonAsMap
 */
export interface ExtendedRevertReasonAsMap {
  /**
   *
   * @type {string}
   * @memberof ExtendedRevertReasonAsMap
   */
  raw: string
  /**
   *
   * @type {number}
   * @memberof ExtendedRevertReasonAsMap
   */
  code: number
  /**
   *
   * @type {string}
   * @memberof ExtendedRevertReasonAsMap
   */
  message: string
}
