/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressParam } from './address-param'
import { TokenInfo } from './token-info'
/**
 *
 * @export
 * @interface Holder
 */
export interface Holder {
  /**
   *
   * @type {AddressParam}
   * @memberof Holder
   */
  address: AddressParam
  /**
   *
   * @type {string}
   * @memberof Holder
   */
  value: string
  /**
   *
   * @type {string}
   * @memberof Holder
   */
  tokenId?: string
  /**
   *
   * @type {TokenInfo}
   * @memberof Holder
   */
  token: TokenInfo
}
