/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface InlineResponse20026
 */
export interface InlineResponse20026 {
  /**
   *
   * @type {string}
   * @memberof InlineResponse20026
   */
  newSmartContracts24h: string
  /**
   *
   * @type {string}
   * @memberof InlineResponse20026
   */
  newVerifiedSmartContracts24h: string
  /**
   *
   * @type {string}
   * @memberof InlineResponse20026
   */
  smartContracts: string
  /**
   *
   * @type {string}
   * @memberof InlineResponse20026
   */
  verifiedSmartContracts: string
}
