/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CoinBalanceHistoryEntry } from './coin-balance-history-entry'
/**
 *
 * @export
 * @interface InlineResponse20017
 */
export interface InlineResponse20017 {
  /**
   *
   * @type {Array<CoinBalanceHistoryEntry>}
   * @memberof InlineResponse20017
   */
  items: Array<CoinBalanceHistoryEntry>
  /**
   *
   * @type {any}
   * @memberof InlineResponse20017
   */
  nextPageParams: any
}
