/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TokenTransfer } from './token-transfer'
/**
 *
 * @export
 * @interface InlineResponse20012
 */
export interface InlineResponse20012 {
  /**
   *
   * @type {Array<TokenTransfer>}
   * @memberof InlineResponse20012
   */
  items: Array<TokenTransfer>
  /**
   *
   * @type {any}
   * @memberof InlineResponse20012
   */
  nextPageParams: any
}
