/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NFTInstance } from './nftinstance'
/**
 *
 * @export
 * @interface InlineResponse20021
 */
export interface InlineResponse20021 {
  /**
   *
   * @type {Array<NFTInstance>}
   * @memberof InlineResponse20021
   */
  items: Array<NFTInstance>
  /**
   *
   * @type {any}
   * @memberof InlineResponse20021
   */
  nextPageParams: any
}
