/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Withdrawal } from './withdrawal'
/**
 *
 * @export
 * @interface InlineResponse20010
 */
export interface InlineResponse20010 {
  /**
   *
   * @type {Array<Withdrawal>}
   * @memberof InlineResponse20010
   */
  items: Array<Withdrawal>
  /**
   *
   * @type {any}
   * @memberof InlineResponse20010
   */
  nextPageParams: any
}
