/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SearchResultAddressOrContract } from './search-result-address-or-contract'
import { SearchResultBlock } from './search-result-block'
import { SearchResultToken } from './search-result-token'
import { SearchResultTransaction } from './search-result-transaction'
/**
 *
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
  /**
   *
   * @type {Array<SearchResultToken | SearchResultAddressOrContract | SearchResultBlock | SearchResultTransaction>}
   * @memberof InlineResponse200
   */
  items: Array<
    | SearchResultToken
    | SearchResultAddressOrContract
    | SearchResultBlock
    | SearchResultTransaction
  >
  /**
   *
   * @type {any}
   * @memberof InlineResponse200
   */
  nextPageParams: any
}
