/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SmartContractForList } from './smart-contract-for-list'
/**
 *
 * @export
 * @interface InlineResponse20025
 */
export interface InlineResponse20025 {
  /**
   *
   * @type {Array<SmartContractForList>}
   * @memberof InlineResponse20025
   */
  items: Array<SmartContractForList>
  /**
   *
   * @type {any}
   * @memberof InlineResponse20025
   */
  nextPageParams: any
}
