/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressWithTxCount } from './address-with-tx-count'
/**
 *
 * @export
 * @interface InlineResponse20011
 */
export interface InlineResponse20011 {
  /**
   *
   * @type {string}
   * @memberof InlineResponse20011
   */
  exchangeRate: string
  /**
   *
   * @type {string}
   * @memberof InlineResponse20011
   */
  totalSupply: string
  /**
   *
   * @type {Array<AddressWithTxCount>}
   * @memberof InlineResponse20011
   */
  items: Array<AddressWithTxCount>
  /**
   *
   * @type {any}
   * @memberof InlineResponse20011
   */
  nextPageParams: any
}
