/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TokenInfo } from './token-info'
/**
 *
 * @export
 * @interface InlineResponse20018
 */
export interface InlineResponse20018 {
  /**
   *
   * @type {Array<TokenInfo>}
   * @memberof InlineResponse20018
   */
  items: Array<TokenInfo>
  /**
   *
   * @type {any}
   * @memberof InlineResponse20018
   */
  nextPageParams: any
}
