/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InternalTransaction } from './internal-transaction'
/**
 *
 * @export
 * @interface InlineResponse20013
 */
export interface InlineResponse20013 {
  /**
   *
   * @type {Array<InternalTransaction>}
   * @memberof InlineResponse20013
   */
  items: Array<InternalTransaction>
  /**
   *
   * @type {any}
   * @memberof InlineResponse20013
   */
  nextPageParams: any
}
