/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TokenBalance } from './token-balance'
/**
 *
 * @export
 * @interface InlineResponse20016
 */
export interface InlineResponse20016 {
  /**
   *
   * @type {Array<TokenBalance>}
   * @memberof InlineResponse20016
   */
  items: Array<TokenBalance>
  /**
   *
   * @type {any}
   * @memberof InlineResponse20016
   */
  nextPageParams: any
}
