/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressParam } from './address-param'
import { DecodedInputLog } from './decoded-input-log'
/**
 *
 * @export
 * @interface Log
 */
export interface Log {
  /**
   *
   * @type {AddressParam}
   * @memberof Log
   */
  address: AddressParam
  /**
   *
   * @type {string}
   * @memberof Log
   */
  blockHash?: string
  /**
   *
   * @type {number}
   * @memberof Log
   */
  blockNumber?: number
  /**
   *
   * @type {string}
   * @memberof Log
   */
  data: string
  /**
   *
   * @type {DecodedInputLog}
   * @memberof Log
   */
  decoded: DecodedInputLog
  /**
   *
   * @type {number}
   * @memberof Log
   */
  index: number
  /**
   *
   * @type {AddressParam}
   * @memberof Log
   */
  smartContract: AddressParam
  /**
   *
   * @type {Array<string>}
   * @memberof Log
   */
  topics: Array<string>
  /**
   *
   * @type {string}
   * @memberof Log
   */
  txHash: string
}
