/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TotalERC721 } from './total-erc721'
/**
 *
 * @export
 * @interface NFTChange
 */
export interface NFTChange {
  /**
   *
   * @type {string}
   * @memberof NFTChange
   */
  direction: string
  /**
   *
   * @type {TotalERC721}
   * @memberof NFTChange
   */
  total: TotalERC721
}
