/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressParam } from './address-param'
import { TokenInfo } from './token-info'
/**
 *
 * @export
 * @interface NFTInstance
 */
export interface NFTInstance {
  /**
   *
   * @type {boolean}
   * @memberof NFTInstance
   */
  isUnique: boolean
  /**
   *
   * @type {string}
   * @memberof NFTInstance
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof NFTInstance
   */
  holderAddressHash?: string
  /**
   *
   * @type {string}
   * @memberof NFTInstance
   */
  imageUrl?: string
  /**
   *
   * @type {string}
   * @memberof NFTInstance
   */
  animationUrl?: string
  /**
   *
   * @type {string}
   * @memberof NFTInstance
   */
  externalAppUrl?: string
  /**
   *
   * @type {any}
   * @memberof NFTInstance
   */
  metadata?: any
  /**
   *
   * @type {AddressParam}
   * @memberof NFTInstance
   */
  owner: AddressParam
  /**
   *
   * @type {TokenInfo}
   * @memberof NFTInstance
   */
  token: TokenInfo
}
