/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OutputAndNames
 */
export interface OutputAndNames {
  /**
   *
   * @type {Array}
   * @memberof OutputAndNames
   */
  output: Array<any>
  /**
   *
   * @type {Array}
   * @memberof OutputAndNames
   */
  names: Array<any>
}
