/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface RawTraceCreateAction
 */
export interface RawTraceCreateAction {
  /**
   *
   * @type {string}
   * @memberof RawTraceCreateAction
   */
  from: string
  /**
   *
   * @type {string}
   * @memberof RawTraceCreateAction
   */
  gas: string
  /**
   *
   * @type {string}
   * @memberof RawTraceCreateAction
   */
  init: string
  /**
   *
   * @type {string}
   * @memberof RawTraceCreateAction
   */
  value: string
}
