/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface StatsResponse
 */
export interface StatsResponse {
  /**
   *
   * @type {string}
   * @memberof StatsResponse
   */
  totalBlocks: string
  /**
   *
   * @type {string}
   * @memberof StatsResponse
   */
  totalAddresses: string
  /**
   *
   * @type {string}
   * @memberof StatsResponse
   */
  totalTransactions: string
  /**
   *
   * @type {number}
   * @memberof StatsResponse
   */
  averageBlockTime: number
  /**
   *
   * @type {string}
   * @memberof StatsResponse
   */
  coinPrice: string
  /**
   *
   * @type {string}
   * @memberof StatsResponse
   */
  totalGasUsed: string
  /**
   *
   * @type {string}
   * @memberof StatsResponse
   */
  transactionsToday: string
  /**
   *
   * @type {string}
   * @memberof StatsResponse
   */
  gasUsedToday: string
  /**
   *
   * @type {any}
   * @memberof StatsResponse
   */
  gasPrices: any
  /**
   *
   * @type {string}
   * @memberof StatsResponse
   */
  staticGasPrice: string
  /**
   *
   * @type {string}
   * @memberof StatsResponse
   */
  marketCap: string
  /**
   *
   * @type {number}
   * @memberof StatsResponse
   */
  networkUtilizationPercentage: number
}
