/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Token
 */
export interface Token {
  /**
   *
   * @type {string}
   * @memberof Token
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof Token
   */
  decimals: string
  /**
   *
   * @type {string}
   * @memberof Token
   */
  symbol: string
  /**
   *
   * @type {string}
   * @memberof Token
   */
  address: string
  /**
   *
   * @type {string}
   * @memberof Token
   */
  type: string
  /**
   *
   * @type {number}
   * @memberof Token
   */
  holders: number
  /**
   *
   * @type {string}
   * @memberof Token
   */
  exchangeRate: string
  /**
   *
   * @type {string}
   * @memberof Token
   */
  totalSupply: string
}
