/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NFTInstance } from './nftinstance'
import { Token } from './token'
/**
 *
 * @export
 * @interface TokenBalance
 */
export interface TokenBalance {
  /**
   *
   * @type {NFTInstance}
   * @memberof TokenBalance
   */
  tokenInstance?: NFTInstance
  /**
   *
   * @type {string}
   * @memberof TokenBalance
   */
  value: string
  /**
   *
   * @type {string}
   * @memberof TokenBalance
   */
  tokenId: string
  /**
   *
   * @type {Token}
   * @memberof TokenBalance
   */
  token: Token
}
