/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface TotalERC1155
 */
export interface TotalERC1155 {
  /**
   *
   * @type {string}
   * @memberof TotalERC1155
   */
  tokenId: string
  /**
   *
   * @type {string}
   * @memberof TotalERC1155
   */
  decimals: string
  /**
   *
   * @type {string}
   * @memberof TotalERC1155
   */
  value: string
}
