/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TotalERC1155 } from './total-erc1155'
/**
 *
 * @export
 * @interface TotalERC1155Batch
 */
export interface TotalERC1155Batch extends Array<TotalERC1155> {}
