/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface TransactionActionUniswapV3MintNFT
 */
export interface TransactionActionUniswapV3MintNFT {
  /**
   *
   * @type {any}
   * @memberof TransactionActionUniswapV3MintNFT
   */
  data: any
  /**
   *
   * @type {string}
   * @memberof TransactionActionUniswapV3MintNFT
   */
  protocol: string
  /**
   *
   * @type {string}
   * @memberof TransactionActionUniswapV3MintNFT
   */
  type: string
}
