/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface WatchlistName
 */
export interface WatchlistName {
  /**
   *
   * @type {string}
   * @memberof WatchlistName
   */
  displayName: string
  /**
   *
   * @type {string}
   * @memberof WatchlistName
   */
  label: string
}
