/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaop3734@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressParam } from './address-param'
/**
 *
 * @export
 * @interface Withdrawal
 */
export interface Withdrawal {
  /**
   *
   * @type {number}
   * @memberof Withdrawal
   */
  index: number
  /**
   *
   * @type {string}
   * @memberof Withdrawal
   */
  amount: string
  /**
   *
   * @type {number}
   * @memberof Withdrawal
   */
  validatorIndex: number
  /**
   *
   * @type {AddressParam}
   * @memberof Withdrawal
   */
  receiver?: AddressParam
  /**
   *
   * @type {number}
   * @memberof Withdrawal
   */
  blockNumber?: number
  /**
   *
   * @type {string}
   * @memberof Withdrawal
   */
  timestamp?: string
}
